### ISSUE TITLE
Why not publish on crates.io?

### ISSUE THREAD

**Issue by andylokandy** [danylaporte/rust-asyncplify#1]
I'm quite surprised to see this awesome crate. But it, maybe for some reason, was forgotten at the corner. Is it WIP or deprecated? 
I really appreciate what you have done.

**Comment by danylaporte** [comment]
Thanks for your interest. I think we can consider this crate as deprecated in favor of [futures-rs](https://github.com/alexcrichton/futures-rs) which will probably become a standard in rust.

**Comment by andylokandy** [comment]
All right. But I think futures-rs' poll model does not so fit for frp purpose. Since we need to register all the end combinators, and there is no any Signal-like mechanism that hold the last value all the time.

**Comment by danylaporte** [comment]
Yeah, you are probably right, but those could be added to future-rs. Ok, you've got me! I will continue the crate 👍
Thank you very much.
